# Generated by Django 6.0.4 on 2026-07-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quamtity',
            new_name='quantity',
        ),
    ]
