# Generated by Django 6.0.4 on 2026-07-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Shipped',
            field=models.BooleanField(default=False),
        ),
    ]
